# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20, unique=True)),
                ('s_create_time', models.DateTimeField(auto_now_add=True)),
                ('s_operate_time', models.DateTimeField(auto_now=True)),
                ('s_img', models.ImageField(null=True, upload_to='upload')),
                ('s_chinese', models.IntegerField(null=True)),
                ('s_math', models.IntegerField(null=True)),
                ('stu_tel', models.CharField(max_length=11, null=True)),
                ('stu_birth', models.DateField(null=True)),
                ('stu_delete', models.BooleanField(default=0)),
                ('stu_sex', models.BooleanField(default=0)),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grade')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_addr', models.CharField(max_length=30)),
                ('stu_age', models.IntegerField()),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
    ]
