# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_g_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='g_name',
        ),
    ]
